services:
  backend:
    build:
      context: ./backend
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./envs/backend.env
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./backend:/app
