# Generated by Django 4.2.1 on 2023-06-06 13:00
import datetime

from django.db import migrations

from helpers.nbp_api_request import fetch_all_currency_data


def load_currency_data(apps, schema_editor):
    CurrencyName = apps.get_model("currencies", "CurrencyName")
    CurrencyDate = apps.get_model("currencies", "CurrencyDate")
    CurrencyValue = apps.get_model("currencies", "CurrencyValue")

    start_date = datetime.date(2005, 1, 2)
    end_date = datetime.date.today()

    data = fetch_all_currency_data(start_date, end_date)

    currency_values = [
        CurrencyValue(
            exchange_rate=rate["mid"],
            currency_name=CurrencyName.objects.get_or_create(name=rate["currency"], code=rate["code"])[0],
            currency_date=CurrencyDate.objects.get_or_create(date=date["effectiveDate"])[0],
        )
        for date in data
        for rate in date["rates"]
    ]
    CurrencyValue.objects.bulk_create(currency_values)


def delete_all_currency_data(apps, schema_editor):
    CurrencyName = apps.get_model("currencies", "CurrencyName")
    CurrencyDate = apps.get_model("currencies", "CurrencyDate")
    CurrencyValue = apps.get_model("currencies", "CurrencyValue")

    CurrencyName.objects.all().delete()
    CurrencyDate.objects.all().delete()
    CurrencyValue.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_currency_data, delete_all_currency_data)]
